### PR TITLE
change datatype and number to task=all

### PR DESCRIPTION
**Pull request by ieguinoa**

### CODE REVIEW

**Comment by ieguinoa** [comment]
this is just to get the input fields right, still need to test the functionality for it, could you check that?

**Comment by CarlosHorro** [comment]
Um... I do not know yet where is the problem but running "full" always finish in error:

`ERROR input files not found or just one input file selected . check the folder or the extension given in input`

choosing whatever multiple or single files.


Example command line:
`mkdir ./out &&  mkdir ./ident_inputs && cp '/tmp/tmpv6JoBi/files/000/dataset_2.dat' './ident_inputs/Galaxy106-__ob__Peptide_Shaker_on_data_90__PSM_Report__cb__.tabular.raw' &&   mkdir ./raws && ln -s '/tmp/tmpv6JoBi/files/000/dataset_3.dat' './raws/ginkgotoxin-ms-switching.raw.raw' && ln -s '/tmp/tmpv6JoBi/files/000/dataset_5.dat' './raws/small.raw.raw' &&  moff_all.py  --tsv_list './ident_inputs/Galaxy106-__ob__Peptide_Shaker_on_data_90__PSM_Report__cb__.tabular.raw'   --raw_list './raws/ginkgotoxin-ms-switching.raw.raw' './raws/small.raw.raw'  --tol 10.0 --mbr on --xic_length 3.0 --rt_peak_win 1.0 --rt_peak_win_match 1.2 --loc_out ./out --peptide_summary && mv ./out/peptide_summary_intensity_moFF_run.tab '/tmp/tmpv6JoBi/files/000/dataset_19.dat'`

**Comment by CarlosHorro** [comment]
After some testing and revision of moff_all.py, it seems we should allow entering more than 1 tsv file as, when mbr=="on", moff_all.py has:
```
if args.tsv_list is not None:
            # input list of raw and tsv file
            if len(args.tsv_list) != len(args.raw_list):
                exit(
                    'Error:  number of the input files is different from the number of raw files')
            # in case list of file as input , mbr_output is written in local folder
            folder = os.path.join('mbr_output')
        
```
so it requires having the same number of tsv and raw files, and now we can only use 1 tsv file per execution. Executing it manually via command line, I have checked that the error disappears when specifying 2 files in --tsv_list (in an example using 2 raw files)...

**Comment by Maux82** [comment]
before of the  control you potsed on line 189 (moff_all.py)  I do 
```
 if  ( args.tsv_list is not None) and  ( args.raw_list is not None) and (len(args.tsv_list)==1) :
        data_temp= pd.read_csv(args.tsv_list[0],sep="\t")
        if moff.check_ps_input_data(data_temp.columns.tolist(), ast.literal_eval(config.get('moFF', 'ps_default_export_v1'))) == 1:
            if  len(data_temp['Spectrum File'].unique())> 1 and len(args.raw_list) > 1:
                output_list_loc=[]
                for file in data_temp['Spectrum File'].unique():
                    data_temp[data_temp['Spectrum File']== file].to_csv(os.path.join(os.path.split(args.tsv_list[0])[0],file.split('.')[0]+ '.txt'), sep='\t' , index=False )
                    output_list_loc.append(os.path.join(os.path.split(args.tsv_list[0])[0],file.split('.')[0]+ '.txt') 
                if len(args.raw_list) != len(output_list_loc):
                    exit('-- Number of raw file is different to the number of input sources detectd in your one input file --')
                args.raw_list= sorted(args.raw_list)
                args.tsv_list= sorted(output_list_loc)
                #clean dataset thta I don use anymore
                del data_temp
                gc.collect()
```
here I check if I have one file in tsv and not None in raw_list , if it so I split the input file in the corrisponding input file and I update the command argument.

Yesterday evening it s worked for me on Galaxy..

**Comment by CarlosHorro** [comment]
Um... sorry, it seems there were something weird with my files, using different ones this specific problem disappeared.

Testing this a bit further, I am noticing another problem: choosing peptide summary = no, the execution finish in error: 

```
Fatal error: Exit code 2 ()
usage: moff_all.py [-h] [--loc_in LOC_IN]
                   [--tsv_list [TSV_LIST [TSV_LIST ...]]]
                   [--raw_list [RAW_LIST [RAW_LIST ...]]] [--sample SAMPLE]
                   [--ext EXT] [--log_label LOG_LABEL] [--w_filt W_FILT]
                   [--out_flag] [--w_comb] [--tol TOL]
                   [--xic_length XIC_LENGTH] [--rt_peak_win RT_PEAK_WIN]
                   [--rt_peak_win_match RT_PEAK_WIN_MATCH]
                   [--raw_repo RAW_REPO] [--loc_out LOC_OUT]
                   [--rt_feat_file RT_FEAT_FILE] [--peptide_summary]
                   [--tag_pepsum TAG_PEPSUM] [--match_filter]
                   [--ptm_file PTM_FILE]
                   [--quantile_thr_filtering QUANTILE_THR_FILTERING]
                   [--sample_size SAMPLE_SIZE] [--mbr MBR] [--cpu CPU_NUM]
moff_all.py: error: unrecognized arguments: mv ./out/*moff_result.txt /tmp/tmpTcFyLu/files/000/dataset_45.dat
```

command line:
`mkdir ./out &&  mkdir ./ident_inputs && cp '/tmp/tmpTcFyLu/files/000/dataset_2.dat' './ident_inputs/1.tabular.raw' &&   mkdir ./raws && ln -s '/tmp/tmpTcFyLu/files/000/dataset_7.dat' './raws/ginkgotoxin-ms-positive.raw.raw' &&  moff_all.py  --tsv_list './ident_inputs/1.tabular.raw'   --raw_list './raws/ginkgotoxin-ms-positive.raw.raw'  --tol 10.0 --mbr off --xic_length 3.0 --rt_peak_win 1.0 --loc_out ./out mv ./out/*moff_result.txt '/tmp/tmpTcFyLu/files/000/dataset_45.dat' && mv ./out/*.log '/tmp/tmpTcFyLu/files/000/dataset_46.dat'`

**Comment by CarlosHorro** [comment]
I think I will regenerate my testing files as it seems I am having unexpected behaviors.

**Pull request merged**
